export const NAV_CHANGED             = 'NAV_CHANGED';

export const AUTH_START              = 'AUTH_START';
export const AUTH_SUCCESS            = 'AUTH_SUCCESS';
export const AUTH_FAIL               = 'AUTH_FAIL';
export const AUTH_LOGOUT             = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH  = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_CLEAR_ERROR        = 'AUTH_CLEAR_ERROR';

export const FETCH_USER_START        = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS      = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL         = 'FETCH_USER_FAIL';

export const REGISTER_START          = 'REGISTER_START';
export const REGISTER_SUCCESS        = 'REGISTER_SUCCESS';
export const REGISTER_FAIL           = 'REGISTER_FAIL';
export const USER_UPDATE_START       = 'USER_UPDATE_START';
export const USER_UPDATE_SUCCESS     = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL        = 'USER_UPDATE_FAIL';

export const FETCH_SEARCH_START      = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_SUCCESS    = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_FAIL       = 'FETCH_SEARCH_FAIL';
export const CHANGE_SEARCH_PLACE     = 'CHANGE_SEARCH_PLACE';
export const USER_LOCATION_DETECTED  = 'USER_LOCATION_DETECTED';
export const CHANGE_SEARCH_MODE      = 'CHANGE_SEARCH_MODE';
export const CHANGE_ACTIVE_MARKER    = 'CHANGE_ACTIVE_MARKER';
export const CHANGE_SEARCH_POPUP     = 'CHANGE_SEARCH_POPUP';
export const CHANGE_SEARCH_OPENFILTERS='CHANGE_SEARCH_OPENFILTERS';

//  filters
export const CHANGE_SEARCH_PADRETIPOFILTERS = 'CHANGE_SEARCH_PADRETIPOFILTERS';
export const CHANGE_SEARCH_TIPOFILTERS      = 'CHANGE_SEARCH_TIPOFILTERS';
export const CHANGE_SEARCH_DESDEFILTERS     = 'CHANGE_SEARCH_DESDEFILTERS';
export const CHANGE_SEARCH_HASTAFILTERS     = 'CHANGE_SEARCH_HASTAFILTERS';
export const CHANGE_SEARCH_DISTANCIAFILTERS = 'CHANGE_SEARCH_DISTANCIAFILTERS';

export const FETCH_MEMBER_START      = 'FETCH_MEMBER_START';
export const FETCH_MEMBER_SUCCESS    = 'FETCH_MEMBER_SUCCESS';
export const FETCH_MEMBER_FAIL       = 'FETCH_MEMBER_FAIL';

export const FETCH_MACHINETYPES_START= 'FETCH_MACHINETYPES_START';
export const FETCH_MACHINETYPES_SUCCESS='FETCH_MACHINETYPES_SUCCESS';
export const FETCH_MACHINETYPES_FAIL = 'FETCH_MACHINETYPES_FAIL';
export const FETCH_MACHINE_START     = 'FETCH_MACHINE_START';
export const FETCH_MACHINE_SUCCESS   = 'FETCH_MACHINE_SUCCESS';
export const FETCH_MACHINE_FAIL      = 'FETCH_MACHINE_FAIL';

export const MAINTYPE_CHANGED        = 'MAINTYPE_CHANGED';
export const OTHERTYPES_CHANGED      = 'OTHERTYPES_CHANGED';
export const MACHINE_SET_CARACTERISTICAS = 'MACHINE_SET_CARACTERISTICAS';
export const MACHINE_ADD_CARACTERISTICA  = 'MACHINE_ADD_CARACTERISTICA';
export const MACHINE_REMOVE_CARACTERISTICA='MACHINE_REMOVE_CARACTERISTICA';

export const CREATE_MACHINE_START    = 'CREATE_MACHINE_START';
export const CREATE_MACHINE_SUCCESS  = 'CREATE_MACHINE_SUCCESS';
export const CREATE_MACHINE_FAIL     = 'CREATE_MACHINE_FAIL';
export const UPDATE_MACHINE_START    = 'UPDATE_MACHINE_START';
export const UPDATE_MACHINE_SUCCESS  = 'UPDATE_MACHINE_SUCCESS';
export const UPDATE_MACHINE_FAIL     = 'UPDATE_MACHINE_FAIL';

export const FETCH_CHATS_START       = 'FETCH_CHATS_START';
export const FETCH_CHATS_SUCCESS     = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAIL        = 'FETCH_CHATS_FAIL';
export const FETCH_MESSAGES_START    = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS  = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAIL     = 'FETCH_MESSAGES_FAIL';
export const FETCH_UNREAD_MESSAGES_START   = 'FETCH_UNREAD_MESSAGES_START';
export const FETCH_UNREAD_MESSAGES_SUCCESS = 'FETCH_UNREAD_MESSAGES_SUCCESS';
export const FETCH_UNREAD_MESSAGES_FAIL    = 'FETCH_UNREAD_MESSAGES_FAIL';
export const SEND_MESSAGE_START            = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS          = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL             = 'SEND_MESSAGE_FAIL';